#!/usr/bin/env bash
set -e

docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.56.2 golangci-lint --timeout 2m run ./... -v
docker run --rm -v $(pwd):/app -w /app quay.io/goswagger/swagger validate docs/api/swagger.yaml
